<Project
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
  ToolsVersion="4.0"
  TreatAsLocalProperty="TaskAssembly"
>
  <Import Project="Snek.props" />

  <!-- Props for local testing, used by the demo project -->
  <PropertyGroup>
    <TaskAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'"
      >$(MSBuildThisFileDirectory)/bin/$(Configuration)/netstandard2.0/Snek.dll</TaskAssembly
    >
    <TaskAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'"
      >$(MSBuildThisFileDirectory)/bin/$(Configuration)/net472/Snek.dll</TaskAssembly
    >
  </PropertyGroup>
</Project>
